network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      addresses:
        - 192.168.201.2/24
      gateway4: 192.168.201.1
      nameservers:
          search: [mydomain, otherdomain]
          addresses: [192.168.201.1, 1.1.1.1]
